FROM python:3.10.4
WORKDIR /opt/backends/
COPY app.py ./
COPY infodb.py ./
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN wget -O backend.zip https://www.dropbox.com/s/apyoabvieotk13s/backend.zip?dl=1
RUN apt install unzip -y
RUN unzip backend.zip
RUN rm backend.zip
RUN apt remove unzip -y
CMD [ "python", "app.py" ]
EXPOSE 5000